<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[DataBase is Connected]]>
    </line>
    <line>
      <![CDATA[DataBase is Close]]>
    </line>
  </reporter-output>
  <suite started-at="2021-11-10T11:40:56 IST" name="Default suite" finished-at="2021-11-10T11:41:17 IST" duration-ms="21216">
    <groups>
    </groups>
    <test started-at="2021-11-10T11:40:56 IST" name="Default test" finished-at="2021-11-10T11:41:17 IST" duration-ms="21216">
      <class name="practies.listnerPracties">
        <test-method is-config="true" signature="configBS()[pri:0, instance:practies.listnerPracties@4f2b503c]" started-at="2021-11-10T11:40:55 IST" name="configBS" finished-at="2021-11-10T11:40:56 IST" duration-ms="433" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[DataBase is Connected]]>
            </line>
          </reporter-output>
        </test-method> <!-- configBS -->
        <test-method is-config="true" signature="configBC()[pri:0, instance:practies.listnerPracties@4f2b503c]" started-at="2021-11-10T11:40:56 IST" name="configBC" finished-at="2021-11-10T11:41:01 IST" duration-ms="5193" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBC -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:practies.listnerPracties@4f2b503c]" started-at="2021-11-10T11:41:01 IST" name="configBM" finished-at="2021-11-10T11:41:05 IST" duration-ms="4392" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method signature="listner()[pri:0, instance:practies.listnerPracties@4f2b503c]" started-at="2021-11-10T11:41:05 IST" name="listner" finished-at="2021-11-10T11:41:05 IST" duration-ms="17" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at practies.listnerPracties.listner(listnerPracties.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listner -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:practies.listnerPracties@4f2b503c]" started-at="2021-11-10T11:41:06 IST" name="configAM" finished-at="2021-11-10T11:41:17 IST" duration-ms="10734" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configAC()[pri:0, instance:practies.listnerPracties@4f2b503c]" started-at="2021-11-10T11:41:17 IST" name="configAC" finished-at="2021-11-10T11:41:17 IST" duration-ms="240" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAC -->
        <test-method is-config="true" signature="configAS()[pri:0, instance:practies.listnerPracties@4f2b503c]" started-at="2021-11-10T11:41:17 IST" name="configAS" finished-at="2021-11-10T11:41:17 IST" duration-ms="24" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[DataBase is Close]]>
            </line>
          </reporter-output>
        </test-method> <!-- configAS -->
      </class> <!-- practies.listnerPracties -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
